#!/usr/bin/env python
import subprocess
import shutil

# depends on pciutils, dmidecode, lshw
def check_installed(program):
    return shutil.which(program)

# commands for info gleaning
bios_info = "sudo dmidecode | grep -A3 'Vendor:'"
system_info = "sudo dmidecode | grep -A7 'System Information'"
cpu_info = "sudo lshw -C cpu | grep -A3 'product:'"
kernel_version = "uname -r"

# print to console
try:
    if check_installed("dmidecode"):
        print(subprocess.check_output(system_info,shell=True).decode())
        print(f"BIOS info:\n {subprocess.check_output(bios_info, shell=True).decode()}")
except subprocess.CalledProcessError:
    print("dmidecode is not installed")

try:
    if check_installed("lshw"):
        print(f"CPU info:\n{subprocess.check_output(cpu_info, shell=True).decode()}")
except subprocess.CalledProcessError:
    print("lshw is not installed")

try:
    if check_installed("uname"):
        print(f"Kernel version: {subprocess.check_output(kernel_version, shell=True).decode()}")
except subprocess.CalledProcessError:
    print("uname is not installed")
